---
- name: Update package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install system packages
  apt:
    name:
      - curl
      - wget
      - unzip
      - git
    state: present

- name: Install Node.js
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
    apt-get install -y nodejs
  args:
    creates: /usr/bin/node

- name: Verify Node.js installation
  command: node --version
  register: node_version
  failed_when: node_version.rc != 0

