---
- name: Update package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install system packages including nginx
  apt:
    name:
      - curl
      - wget
      - unzip
      - git
      - nginx
    state: present

- name: Add NodeSource repository
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add NodeSource repository
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_18.x jammy main"
    state: present
    update_cache: yes

- name: Install Node.js
  apt:
    name: nodejs
    state: present

