- name: Deploy Quiz Application
  hosts: all
  become: yes
  gather_facts: no
  roles:
    - common

- name: Configure Web Server
  hosts: web_servers
  become: yes
  roles:
    - web

- name: Configure API Server
  hosts: api_servers
  become: yes
  roles:
    - api

- name: Final Verification
  hosts: all
  become: no
  tasks:
    - name: Wait for API service to be ready
      wait_for:
        port: "{{ app_port }}"
        host: "0.0.0.0"
        delay: 5
        timeout: 30
      when: inventory_hostname in groups['api_servers']

    - name: Wait for web service to be ready
      wait_for:
        port: "{{ web_port }}"
        host: "0.0.0.0"
        delay: 5
        timeout: 30
      when: inventory_hostname in groups['web_servers']

    - name: Display deployment info
      debug:
        msg: |
          Deployment successful!
          Frontend: http://{{ hostvars[groups['web_servers'][0]]['ansible_host'] }}
          API: http://{{ hostvars[groups['api_servers'][0]]['ansible_host'] }}:{{ app_port }}
      run_once: true
      when: inventory_hostname == groups['all'][0]