---
- name: Remove default nginx content
  file:
    path: /var/www/html/index.nginx-debian.html
    state: absent

- name: Create web directory
  file:
    path: "{{ web_dir }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'

- name: Deploy frontend files
  copy:
    src: "../../../../frontend/"
    dest: "{{ web_dir }}/"
    owner: www-data
    group: www-data
    mode: '0644'
    directory_mode: '0755'


- name: Configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
    backup: yes
  notify: restart nginx

- name: Start and enable nginx
  systemd:
    name: nginx
    state: started
    enabled: yes